// Generated by Text-to-CAD: 20mm long shaft
// Define constants in millimeters
shaftDiam = 5.0 // shaft diameter
shaftLength = 20.0 // shaft length
// create a sketch on the 'XY' plane
sketch000 = startSketchOn('XY')
// create circular sketch profile using half the shaft diameter
profile000 = circle({center: [0.000000, 0.000000], radius: shaftDiam / 2}, sketch000, $arc001)
// extrude the sketch profile the length of the shaft
solidShaft = extrude(shaftLength, [profile000])

// Define constants for the top
shaftTopDiam = 10.0 // top diameter
shaftTopLength = 10.0 // top length
// create a new sketch for the top on the 'XY' plane
sketch001 = startSketchOn('XY')
// create circular sketch profile for the top
profile001 = circle({center: [0.000000, 0.000000], radius: shaftTopDiam / 2}, sketch001, $arc002)
// extrude the sketch profile for the top
solidTop = extrude(shaftTopLength, [profile001])